# Configuración del servidor
server.port=8082

# Configuración de MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/compraventas
spring.data.mongodb.database=compraventas

# URLs de los microservicios externos
servicios.productos.url=http://localhost:8080/
servicios.usuarios.url=http://localhost:8081/

# Logging
logging.level.es.um.arso.compraventa=DEBUG
