server.port=8083

spring.application.name=compraventa
spring.main.banner-mode=off

spring.data.mongodb.uri=mongodb://mongo:27017/compraventas
spring.data.mongodb.database=compraventas_db

servicios.usuarios.url=http://usuarios:8081/
servicios.productos.url=http://productos:8082/

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=arso
spring.rabbitmq.password=arso

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

logging.level.es.um.arso.compraventa=DEBUG

jwt.secret=arso-secret
jwt.cookie.name=jwt
