server.port=8080
spring.application.name=pasarela

zuul.sensitiveHeaders=

zuul.routes.usuarios.path=/usuarios/**
zuul.routes.usuarios.url=http://usuarios:8081/api/usuarios

zuul.routes.productos.path=/productos/**
zuul.routes.productos.url=http://productos:8082/productos

zuul.routes.compraventa.path=/compraventas/**
zuul.routes.compraventa.url=http://compraventa:8083/compraventas

zuul.routes.valoraciones.path=/valoraciones/**
zuul.routes.valoraciones.url=http://valoraciones:8084/api/valoraciones

servicios.usuarios.url=http://usuarios:8081/

jwt.secret=arso-secret
jwt.access.expirationSeconds=900
jwt.refresh.expirationSeconds=2592000
jwt.refresh.cookie.name=refreshToken
jwt.refresh.cookie.maxAge=2592000
jwt.refresh.cookie.path=/
jwt.refresh.cookie.secure=false

spring.security.oauth2.client.registration.github.clientId=Ov23liJmFMkBMfgi2mPw
spring.security.oauth2.client.registration.github.clientSecret=17e00edf0fc4bb76b684b8e25613075e668d3d19
spring.security.oauth2.client.registration.github.scope=read:user,user:email
